name: Lang tests

on: [pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v6.0.0

      # https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2.36.0
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, curl, dom, fileinfo, iconv, intl, json, mbstring, pdo_sqlite, imagick, posix, simplexml, xml, xmlwriter
          coverage: none

      - name: Install dependencies
        run: cd api && composer install --prefer-dist --no-progress

      - name: Validate JSON files
        run: |
          find translations -type f -name "*.json" -exec jq . {} \; || exit 1

      - name: Check JSON keys are in alphabetical order
        run: |
          for file in $(find translations -type f -name "*.json"); do
            jq -e 'keys == (keys | sort)' "$file" > /dev/null || {
              echo "ERROR: Keys in $file are not in alphabetical order"
              exit 1
            }
          done

      - name: Check for missing translations for the API [en_US]
        run: |
          cd api && php bin/console debug:trans --only-missing -n en_US
